version: '3'

services:
  php:
    container_name: php
    build: ./php
    volumes:
      - ./../server:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./../server:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:latest
    container_name: db-host
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ../db/init_db:/docker-entrypoint-initdb.d